esphome:
  name: t-dongle-s3
  includes:
    - t-dongle-s3/tft_espi_display.h
    - t-dongle-s3/Free_Fonts.h
  libraries:
    - SPI
    - FS
    - SPIFFS
    - tdongles3=https://github.com/bibach/lilygo-t-dongle-s3-esphome.git

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.0.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connect fails
  ap:
    ssid: "T-Dongle-S3"
    password: !secret ap_password

time:
  - platform: homeassistant
    id: ha_time

interval:
  - interval: 1s
    then:
    - lambda: |-
        // displayControllerComponent->clear();
        displayControllerComponent->drawBar();
        displayControllerComponent->drawString(id(ha_time).now().strftime("%Y-%m-%d %H:%M:%S:%S"));

switch:
  - platform: gpio
    pin: GPIO38
    name: "Backlight"
    id: backlight
    internal: true
    restore_mode: RESTORE_DEFAULT_ON

custom_component:
    lambda: |-
        App.register_component(displayControllerComponent);
        return {displayControllerComponent};
    id: displayComponent
